### ISSUE TITLE
GitHub Pages

### ISSUE THREAD

**Issue by Naeem-ur-rahman** [aliyabatoolalvi/My-portfolio#1]
In settings on Pages deploy your site from the main branch.

**Comment by aliyabatoolalvi** [comment]
I have done that, now site is live at : https://aliyabatoolalvi.github.io/My-portfolio/
Thank you.

**Comment by Naeem-ur-rahman** [comment]
Nice. Also add this link into the repository About section. So anyone can see your portfolio

**Comment by aliyabatoolalvi** [comment]
Done
